#include <stdio.h>
#include <assert.h>
#include "libft.h"

void test_ft_isalnum(void);
void test_ft_isprint(void);
void test_ft_memcpy(void);
void test_ft_putendl_fd(void);
void test_ft_strchr(void);
void test_ft_strlcat(void);
void test_ft_strncmp(void);
void test_ft_substr(void);
void test_ft_atoi(void);
void test_ft_isalpha(void);
void test_ft_itoa(void);
void test_ft_memmove(void);
void test_ft_putnbr_fd(void);
void test_ft_strdup(void);
void test_ft_strlcpy(void);
void test_ft_strnstr(void);
void test_ft_tolower(void);
void test_ft_bzero(void);
void test_ft_isascii(void);
void test_ft_memchr(void);
void test_ft_memset(void);
void test_ft_putstr_fd(void);
void test_ft_striteri(void);
void test_ft_strlen(void);
void test_ft_strrchr(void);
void test_ft_toupper(void);
void test_ft_calloc(void);
void test_ft_isdigit(void);
void test_ft_memcmp(void);
void test_ft_putchar_fd(void);
void test_ft_split(void);
void test_ft_strjoin(void);
void test_ft_strmapi(void);
void test_ft_strtrim(void);
void test_ft_putendl_fd(void);
void test_ft_strch(void);
void test_ft_strdup(void);

int main(void)
{
   test_ft_isalnum();
printf("\n--------------------------\n");
test_ft_isprint();
printf("\n--------------------------\n");
test_ft_memcpy();
printf("\n--------------------------\n");
test_ft_putendl_fd();
printf("\n--------------------------\n");
test_ft_strchr();
printf("\n--------------------------\n");
test_ft_strlcat();
printf("\n--------------------------\n");
test_ft_strncmp();
printf("\n--------------------------\n");
test_ft_substr();
printf("\n--------------------------\n");
test_ft_atoi();
printf("\n--------------------------\n");
test_ft_isalpha();
printf("\n--------------------------\n");
test_ft_itoa();
printf("\n--------------------------\n");
test_ft_memmove();
printf("\n--------------------------\n");
test_ft_putnbr_fd();
printf("\n--------------------------\n");
test_ft_strdup();
printf("\n--------------------------\n");
test_ft_strlcpy();
printf("\n--------------------------\n");
test_ft_strnstr();
printf("\n--------------------------\n");
test_ft_tolower();
printf("\n--------------------------\n");
test_ft_bzero();
printf("\n--------------------------\n");
test_ft_isascii();
printf("\n--------------------------\n");
test_ft_memchr();
printf("\n--------------------------\n");
test_ft_memset();
printf("\n--------------------------\n");
test_ft_putstr_fd();
printf("\n--------------------------\n");
test_ft_striteri();
printf("\n--------------------------\n");
test_ft_strlen();
printf("\n--------------------------\n");
test_ft_strrchr();
printf("\n--------------------------\n");
test_ft_toupper();
printf("\n--------------------------\n");
test_ft_calloc();
printf("\n--------------------------\n");
test_ft_isdigit();
printf("\n--------------------------\n");
test_ft_memcmp();
printf("\n--------------------------\n");
test_ft_putchar_fd();
printf("\n--------------------------\n");
test_ft_split();
printf("\n--------------------------\n");
test_ft_strjoin();
printf("\n--------------------------\n");
test_ft_strmapi();
printf("\n--------------------------\n");
test_ft_strtrim();
printf("\n--------------------------\n");

    printf("\nTested by laumoral \n");

    return (0);
}